name: simple_isolate
description: Simplified Dart isolates.
version: 1.5.0
homepage: https://github.com/flutter-cavalry/simple_isolate

environment:
  sdk: ">=2.13.0 <4.0.0"

dev_dependencies:
  mgenware_dart_lints: ^6.5.2
  test: ^1.16.0
