name: simple_isolate
description: Simplified Dart isolates.
version: 1.1.1
homepage: https://github.com/flutter-cavalry/simple_isolate

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  mgenware_dart_lints: ^2.1.0
  test: ^1.16.0
